name: ble_ex
description: A Flutter library based on flutter_reactive_ble. Added more operations for BLE communication.
version: 1.0.1
homepage: https://github.com/featherJ/ble_ex
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: #5.2.0
    git:
      url: https://github.com/Sulisong/flutter_reactive_ble.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  plugin:
    platforms:
      android:
        default_package: ble_ex
      ios:
        default_package: ble_ex
